### ISSUE TITLE
 Preview image error when viewing model info page

### ISSUE THREAD

**Issue by blaqsirens** [cdb-boop/ComfyUI-Model-Manager#3]
Ever since commit 35878d85147c374821098188b76aa1efff8927d8 I've been getting an error when viewing the model info page. The preview image shows up as a broken image link and I get this endlessly repeating error:

![firefox_20240924_012533](https://github.com/user-attachments/assets/b0a3bfb7-2fba-4056-9b25-b6f12864282c)

Error handling request
Traceback (most recent call last):
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 75, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Model-Manager\__init__.py", line 593, in get_model_preview
    head, extension = split_valid_ext(path, preview_extensions)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Software\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Model-Manager\__init__.py", line 68, in split_valid_ext
    sl = s.lower()
         ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

Commit 5521e696e50d31a64efd96739dc2a42b7cd2628f and back work as expected. Could this be another issue with Firefox? Amazing additions to this extension btw.

**Comment by cdb-boop** [comment]
I pushed a debug print. Can you update and tell me what the command line outputs when it breaks?

It should be something like `URL: {request.url}; URI: {uri}; Image Format: {response_image_format}`.

**Comment by blaqsirens** [comment]
URL: http://127.0.0.1:8188/model-manager/preview/get/%2Floras%2F1%2FArtists%2F_GTsuya_Studio%2FPhilippe%20Caza%20%5BGTsuya%5D_v1.preview.png?v=1727141051541368200; URI: %2Floras%2F1%2FArtists%2F_GTsuya_Studio%2FPhilippe Caza [GTsuya]_v1.preview.png; Image Format: None

**Comment by cdb-boop** [comment]
Update and tell me if my patch fixed it.

**Comment by blaqsirens** [comment]
Yep that fixed it! Thanks again!
